import java.util.Timer;
import java.util.TimerTask;
import java.util.Random;
import javax.swing.ImageIcon;


/**
 *
 * @author Kevin
 */
public class Dados extends javax.swing.JFrame {

    String [] Carasd = {"dados1.png","dados2.png","dados3.png","dados4.png","dados5.png","dados6.png"};
    Timer time, time1;
    Random ram = new Random();
    Hilo hiloPrueba;
    
    public Dados() {
        initComponents();
    }
 public class Hilo extends Thread{
    @Override
        public void run(){
            time = new Timer();
            time1 = new Timer();
           
            TimerTask task = new TimerTask() {
                 @Override
                 public void run() {
                     LabelDadoIzq.setIcon(new ImageIcon("Carasdados/" + Carasd[ram.nextInt(6)]));
                     LabelDadoDer.setIcon(new ImageIcon("Carasdados/" + Carasd[ram.nextInt(6)])); 
                     
                     time.cancel();
                 }
             };
            TimerTask task1 = new TimerTask() {
                 @Override
                 public void run() {
                     LabelDadoIzq.setIcon(new ImageIcon("Carasdados/" + Carasd[ram.nextInt(6)]));
                     LabelDadoDer.setIcon(new ImageIcon("Carasdados/" + Carasd[ram.nextInt(6)]));
                 }
             };
            time1.schedule(task,1000); 
            time.scheduleAtFixedRate(task1, 0, 1);
           
            }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelDadoIzq = new javax.swing.JLabel();
        LabelDadoDer = new javax.swing.JLabel();
        TirarButtom = new javax.swing.JButton();
        VolverButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CASINO");

        LabelDadoIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carasdados/dados1.png"))); // NOI18N
        LabelDadoIzq.setText("jLabel2");

        LabelDadoDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Carasdados/dados5.png"))); // NOI18N
        LabelDadoDer.setText("jLabel3");

        TirarButtom.setText("Tirar");
        TirarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TirarButtomActionPerformed(evt);
            }
        });

        VolverButtom.setText("<- volver");
        VolverButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(LabelDadoIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(LabelDadoDer, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(239, 239, 239)
                                .addComponent(jLabel1)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TirarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(VolverButtom)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDadoIzq)
                    .addComponent(LabelDadoDer))
                .addGap(18, 18, 18)
                .addComponent(TirarButtom, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VolverButtom)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtomActionPerformed
       MainCasino Back = new MainCasino();
        Back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VolverButtomActionPerformed

    private void TirarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TirarButtomActionPerformed
        hiloPrueba  = new Hilo();
    hiloPrueba.start();
    
    }//GEN-LAST:event_TirarButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelDadoDer;
    private javax.swing.JLabel LabelDadoIzq;
    private javax.swing.JButton TirarButtom;
    private javax.swing.JButton VolverButtom;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
