import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;

/**
 *
 * @author Kevin
 */
public class Ruleta extends javax.swing.JFrame {

    String [] Formasruleta = {"Imagen1.jpeg" , "Imagen2.jpeg", "Imagen3.jpeg", "Imagen4.jpeg", "Imagen5.jpeg", "Imagen6.jpeg", "Imagen7.jpeg", "Imagen8.jpeg", "Imagen9.jpeg","Imagen10.jpeg","Imagen11.jpeg","Imagen12.jpeg"};
    Timer time;
    Random random = new Random();
    HiloRuleta hilo1  = new HiloRuleta();
    
    
    
    public Ruleta() {
        initComponents();
    }

    
    public class HiloRuleta extends Thread{
       @Override
       public void run(){
        time = new Timer();
        TimerTask task = new TimerTask(){
            @Override
            public void run(){
                LabelForma1.setIcon(new ImageIcon("FormasRuleta/" + Formasruleta[random.nextInt(12)]));
                LabelForma2.setIcon(new ImageIcon("FormasRuleta/" + Formasruleta[random.nextInt(12)]));
                LabelForma3.setIcon(new ImageIcon("FormasRuleta/" + Formasruleta[random.nextInt(12)]));
                LabelForma4.setIcon(new ImageIcon("FormasRuleta/" + Formasruleta[random.nextInt(12)]));
                LabelForma5.setIcon(new ImageIcon("FormasRuleta/" + Formasruleta[random.nextInt(12)]));
            }
        };
        time.scheduleAtFixedRate(task, 0, 100);
       }
        public void Cancel(){
           time.cancel();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        GirarButtom = new javax.swing.JButton();
        DetenerButtom = new javax.swing.JButton();
        LabelForma1 = new javax.swing.JLabel();
        LabelForma2 = new javax.swing.JLabel();
        LabelForma3 = new javax.swing.JLabel();
        LabelForma4 = new javax.swing.JLabel();
        LabelForma5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("RULETA");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ruleta/descarga.png"))); // NOI18N

        jButton1.setText("<- Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        GirarButtom.setText("Girar");
        GirarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirarButtomActionPerformed(evt);
            }
        });

        DetenerButtom.setText("Detener");
        DetenerButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetenerButtomActionPerformed(evt);
            }
        });

        LabelForma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormasRuleta/Imagen10.jpeg"))); // NOI18N
        LabelForma1.setText("jLabel3");

        LabelForma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormasRuleta/Imagen5.jpeg"))); // NOI18N
        LabelForma2.setText("jLabel4");

        LabelForma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormasRuleta/Imagen7.jpeg"))); // NOI18N
        LabelForma3.setText("jLabel5");

        LabelForma4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormasRuleta/Imagen3.jpeg"))); // NOI18N
        LabelForma4.setText("jLabel6");

        LabelForma5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FormasRuleta/Imagen8.jpeg"))); // NOI18N
        LabelForma5.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(197, 197, 197))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LabelForma1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(LabelForma2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelForma3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(LabelForma4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelForma5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GirarButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(DetenerButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelForma1)
                        .addComponent(LabelForma2)
                        .addComponent(LabelForma3)
                        .addComponent(LabelForma4))
                    .addComponent(LabelForma5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GirarButtom)
                    .addComponent(DetenerButtom))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GirarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirarButtomActionPerformed
        hilo1 = new HiloRuleta();
        hilo1.start();
    }//GEN-LAST:event_GirarButtomActionPerformed

    private void DetenerButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetenerButtomActionPerformed
        hilo1.Cancel();
    }//GEN-LAST:event_DetenerButtomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainCasino Back = new MainCasino();
        Back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ruleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DetenerButtom;
    private javax.swing.JButton GirarButtom;
    private javax.swing.JLabel LabelForma1;
    private javax.swing.JLabel LabelForma2;
    private javax.swing.JLabel LabelForma3;
    private javax.swing.JLabel LabelForma4;
    private javax.swing.JLabel LabelForma5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
